version: '3.4'

services:
  common: &BASE
    image: cypress-toolkit:latest
    build:
      context: .
      args:
        - BUNDLE_GITHUB__COM=${BUNDLE_GITHUB__COM}
  
  build:
    <<: *BASE
    command: yarn prepare
